const express = require('express')
const router = express.Router()
const glvRoute = require('./glv.route')
const studentRoute = require('./student.route')
const classRoute = require('./class.route')
const scoreRoute = require('./score.route')
const courseRoute = require('./course.route')
const gradeRoute = require('./grade.route')
const attendanceRoute = require('./attendance.route')
const { requireAuthentication } = require('../middlewares/auth')
const verifyRoles = require('../middlewares/verifyRole')
const ROLES_LIST = require('../config/roles_list')

router.use('/glv',glvRoute)
router.use('/students',studentRoute)
router.use('/classes',classRoute)
router.use('/score',scoreRoute)
router.use('/course',courseRoute)
router.use('/grade',gradeRoute)
router.use('/attendance',attendanceRoute)
router.use('/auth',require('./auth.route'))
router.use('/sacrament',require('./sacrament.route'))

module.exports = router